//
//  StreamsAPIParserTests.swift
//  iOSPlayerSDKTests
//
//  Tests for StreamsAPIParser response parsing.
//

import XCTest
@testable import TPStreamsSDK

final class StreamsAPIParserTests: XCTestCase {

    private let parser = StreamsAPIParser()

    // MARK: - Video Detail Parsing

    func testParseVideoDetailReturnsValidAsset() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.id, "asset-123")
        XCTAssertEqual(asset.title, "Test Video Title")
        XCTAssertEqual(asset.contentType, "video")
        XCTAssertEqual(asset.folderTree, "Root/Section/Lesson")
        XCTAssertEqual(asset.drmContentId, "drm-content-123")
    }

    func testParseVideoDetailReturnsVideoWithCorrectFields() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertNotNil(asset.video)
        XCTAssertEqual(asset.video?.id, "video-456")
        XCTAssertEqual(asset.video?.playbackURL, "https://app.tpstreams.com/hls/abc123/master.m3u8")
        XCTAssertEqual(asset.video?.status, "Ready")
        XCTAssertEqual(asset.video?.duration ?? 0, 3600.5, accuracy: 0.01)
        XCTAssertEqual(asset.video?.thumbnailURL, "https://example.com/thumb.jpg")
        XCTAssertNil(asset.liveStream)
    }

    func testParseVideoDetailParsesDRMEncryptedVideo() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertTrue(asset.video?.drmEncrypted ?? false)
        XCTAssertTrue(asset.isDrmEncrypted)
        XCTAssertEqual(asset.video?.contentProtectionType, .drm)
    }

    func testParseVideoDetailParsesSubtitleTracks() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        let tracks = asset.video?.tracks ?? []
        XCTAssertEqual(tracks.count, 2)
        XCTAssertEqual(tracks[0].language, "en")
        XCTAssertFalse(tracks[0].isAutoGenerated)
        XCTAssertEqual(tracks[1].language, "es")
        XCTAssertTrue(tracks[1].isAutoGenerated)
    }

    func testParseVideoDetailPlaybackURLComputedProperty() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.playbackURL, "https://app.tpstreams.com/hls/abc123/master.m3u8")
    }

    // MARK: - Live Stream Parsing

    func testParseLiveStreamDetail() throws {
        let data = try serializeJSON(TestJSON.streamsLiveStreamDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.id, "live-789")
        XCTAssertEqual(asset.title, "Live Class")
        XCTAssertNil(asset.video)
        XCTAssertNotNil(asset.liveStream)
    }

    func testParseLiveStreamFields() throws {
        let data = try serializeJSON(TestJSON.streamsLiveStreamDetail)
        let asset = try parser.parseAsset(data: data)

        let liveStream = asset.liveStream
        XCTAssertEqual(liveStream?.status, "Streaming")
        XCTAssertEqual(liveStream?.hlsUrl, "https://example.com/live.m3u8")
        XCTAssertTrue(liveStream?.transcodeRecordedVideo ?? false)
        XCTAssertEqual(liveStream?.noticeMessage, "Starting soon!")
        XCTAssertFalse(liveStream?.enableDRM ?? true)
    }

    func testParseLiveStreamIsStreaming() throws {
        let data = try serializeJSON(TestJSON.streamsLiveStreamDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertTrue(asset.liveStream?.isStreaming ?? false)
    }

    func testParseLiveStreamPlaybackURLReturnsHLSUrl() throws {
        let data = try serializeJSON(TestJSON.streamsLiveStreamDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.playbackURL, "https://example.com/live.m3u8")
    }

    // MARK: - AES Encrypted Video

    func testParseAESEncryptedVideo() throws {
        let data = try serializeJSON(TestJSON.streamsAESEncryptedVideo)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.id, "aes-asset-1")
        XCTAssertNotNil(asset.video)
        XCTAssertFalse(asset.video?.drmEncrypted ?? true, "AES video should not be DRM encrypted")
        XCTAssertEqual(asset.video?.contentProtectionType, .aes)
        XCTAssertTrue(asset.video?.isAESEncrypted ?? false)
    }

    // MARK: - Video Without Tracks

    func testParseVideoWithoutTracks() throws {
        let data = try serializeJSON(TestJSON.videoNoTracks)
        let asset = try parser.parseAsset(data: data)

        XCTAssertNotNil(asset.video)
        XCTAssertTrue(asset.video?.tracks.isEmpty ?? false)
    }

    // MARK: - Missing Required Fields

    func testParseThrowsOnMissingID() {
        let json: [String: Any] = [
            "title": "Title",
            "type": "video"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnMissingTitle() {
        let json: [String: Any] = [
            "id": "123",
            "type": "video"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnMissingContentType() {
        let json: [String: Any] = [
            "id": "123",
            "title": "Title"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnEmptyData() {
        let data = Data()
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    // MARK: - Key Identifier

    func testAssetKeyIdentifierReturnsAssetId() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.keyIdentifier, asset.id)
    }

    // MARK: - Video Without Playback URL

    func testParseVideoWithMissingPlaybackURLReturnsNilVideo() {
        let json: [String: Any] = [
            "id": "123",
            "title": "Title",
            "type": "video",
            "video": [
                "status": "Ready"
            ]
        ]
        let data = try! serializeJSON(json)
        let asset = try! parser.parseAsset(data: data)
        XCTAssertNil(asset.video)
    }

    // MARK: - Video Without Status

    func testParseVideoWithMissingStatusReturnsNilVideo() {
        let json: [String: Any] = [
            "id": "123",
            "title": "Title",
            "type": "video",
            "video": [
                "playback_url": "https://example.com/video.m3u8"
            ]
        ]
        let data = try! serializeJSON(json)
        let asset = try! parser.parseAsset(data: data)
        XCTAssertNil(asset.video)
    }

    // MARK: - Duration Defaults

    func testParseVideoWithMissingDurationDefaultsToZero() {
        let json: [String: Any] = [
            "id": "123",
            "title": "Title",
            "type": "video",
            "video": [
                "playback_url": "https://example.com/video.m3u8",
                "status": "Ready"
            ]
        ]
        let data = try! serializeJSON(json)
        let asset = try! parser.parseAsset(data: data)
        XCTAssertEqual(asset.video?.duration, 0.0)
    }

    // MARK: - Is DRM Encrypted

    func testNonDRMVideoIsNotDrmEncrypted() throws {
        let json: [String: Any] = [
            "id": "123",
            "title": "Title",
            "type": "video",
            "video": [
                "id": "v1",
                "playback_url": "https://example.com/video.m3u8",
                "status": "Ready",
                "content_protection_type": "aes"
            ]
        ]
        let data = try! serializeJSON(json)
        let asset = try! parser.parseAsset(data: data)
        XCTAssertFalse(asset.isDrmEncrypted)
    }

    func testDRMVideoIsDrmEncrypted() throws {
        let data = try serializeJSON(TestJSON.streamsVideoDetail)
        let asset = try parser.parseAsset(data: data)
        XCTAssertTrue(asset.isDrmEncrypted)
    }

    // MARK: - Live Stream with DRM

    func testParseLiveStreamWithDRM() {
        let json: [String: Any] = [
            "id": "live-drm",
            "title": "DRM Live",
            "type": "live",
            "live_stream": [
                "status": "Streaming",
                "hls_url": "https://example.com/live.m3u8",
                "transcode_recorded_video": false,
                "chat_embed_url": "https://example.com/chat",
                "enable_drm": true
            ]
        ]
        let data = try! serializeJSON(json)
        let asset = try! parser.parseAsset(data: data)
        XCTAssertTrue(asset.isDrmEncrypted)
        XCTAssertTrue(asset.liveStream?.enableDRM ?? false)
    }

    // MARK: - Helper

    private func serializeJSON(_ dict: [String: Any]) throws -> Data {
        try JSONSerialization.data(withJSONObject: dict)
    }
}
