//
//  SubtitleTrackTests.swift
//  iOSPlayerSDKTests
//
//  Tests for SubtitleTrack initialization, validation, and computed properties.
//

import XCTest
@testable import TPStreamsSDK

final class SubtitleTrackTests: XCTestCase {

    // MARK: - Valid Initialization

    func testValidTrackInitializesSuccessfully() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "https://example.com/en.vtt",
            "subtitle_type": "Manual"
        ])
        XCTAssertNotNil(track)
        XCTAssertEqual(track?.language, "en")
        XCTAssertEqual(track?.url, "https://example.com/en.vtt")
        XCTAssertFalse(track?.isAutoGenerated ?? true)
    }

    func testAutoGeneratedTrackInitializes() {
        let track = SubtitleTrack(from: [
            "language": "es",
            "url": "https://example.com/es.vtt",
            "subtitle_type": "Auto Generated"
        ])
        XCTAssertNotNil(track)
        XCTAssertTrue(track?.isAutoGenerated ?? false)
    }

    // MARK: - Display Name

    func testDisplayNameForManualTrack() {
        let track = SubtitleTrack.make(language: "en", isAutoGenerated: false)
        // LocalizedName for "en" is typically "English"
        XCTAssertTrue(track.displayName.contains("English") || track.displayName == "en")
        XCTAssertFalse(track.displayName.contains("(Auto)"))
    }

    func testDisplayNameForAutoGeneratedTrack() {
        let track = SubtitleTrack.make(language: "en", isAutoGenerated: true)
        XCTAssertTrue(track.displayName.contains("(Auto)"))
    }

    func testDisplayNameForUnknownLanguageFallsBackToCode() {
        let track = SubtitleTrack(from: [
            "language": "xyz",
            "url": "https://example.com/xyz.vtt",
            "subtitle_type": "Manual"
        ])
        XCTAssertNotNil(track)
        // Unknown language code should fall back to the code itself
        XCTAssertTrue(track?.displayName.contains("xyz") ?? false)
    }

    // MARK: - Validation: Missing Language

    func testInitFailsWithoutLanguage() {
        let track = SubtitleTrack(from: [
            "url": "https://example.com/en.vtt"
        ])
        XCTAssertNil(track)
    }

    // MARK: - Validation: Missing URL

    func testInitFailsWithoutURL() {
        let track = SubtitleTrack(from: [
            "language": "en"
        ])
        XCTAssertNil(track)
    }

    // MARK: - Validation: Empty Dictionary

    func testInitFailsWithEmptyDictionary() {
        let track = SubtitleTrack(from: [:])
        XCTAssertNil(track)
    }

    // MARK: - Validation: URL Requirements

    func testInitFailsWithNonHTTPURL() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "ftp://example.com/en.vtt"
        ])
        XCTAssertNil(track)
    }

    func testInitFailsWithNonVTTExtension() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "https://example.com/en.srt"
        ])
        XCTAssertNil(track)
    }

    func testInitFailsWithNoExtension() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "https://example.com/en"
        ])
        XCTAssertNil(track)
    }

    func testInitSucceedsWithHTTPURL() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "http://example.com/en.vtt"
        ])
        XCTAssertNotNil(track)
    }

    func testInitSucceedsWithHTTPSURL() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "https://example.com/en.vtt"
        ])
        XCTAssertNotNil(track)
    }

    func testInitFailsWithMalformedURL() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "not-a-url"
        ])
        XCTAssertNil(track)
    }

    // MARK: - Missing subtitle_type Defaults to Non-Auto

    func testMissingSubtitleTypeDefaultsToNonAuto() {
        let track = SubtitleTrack(from: [
            "language": "en",
            "url": "https://example.com/en.vtt"
        ])
        XCTAssertNotNil(track)
        XCTAssertFalse(track?.isAutoGenerated ?? true)
    }

    // MARK: - Equatable

    func testEqualTracksAreEqual() {
        let track1 = SubtitleTrack.make(language: "en", url: "https://example.com/en.vtt")
        let track2 = SubtitleTrack.make(language: "en", url: "https://example.com/en.vtt")
        XCTAssertEqual(track1, track2)
    }

    func testDifferentTracksAreNotEqual() {
        let track1 = SubtitleTrack.make(language: "en", url: "https://example.com/en.vtt")
        let track2 = SubtitleTrack.make(language: "es", url: "https://example.com/es.vtt")
        XCTAssertNotEqual(track1, track2)
    }

    func testSameLanguageDifferentURLNotEqual() {
        let track1 = SubtitleTrack.make(language: "en", url: "https://example.com/v1/en.vtt")
        let track2 = SubtitleTrack.make(language: "en", url: "https://example.com/v2/en.vtt")
        XCTAssertNotEqual(track1, track2)
    }

    // MARK: - Case Insensitive Language

    func testUpperCaseLanguageInitializes() {
        let track = SubtitleTrack(from: [
            "language": "EN",
            "url": "https://example.com/EN.vtt"
        ])
        XCTAssertNotNil(track)
        XCTAssertEqual(track?.language, "EN")
    }
}
