//
//  TestHelpers.swift
//  iOSPlayerSDKTests
//
//  Shared helpers for the test suite.
//

import XCTest
import XCTest
import Foundation
import RealmSwift
@testable import TPStreamsSDK

// MARK: - Realm In-Memory Setup

/// Configures Realm to use an in-memory store for tests.
/// Call this in `setUp()` of any test that touches Realm.
func configureInMemoryRealm(for test: XCTestCase) {
    var config = Realm.Configuration(inMemoryIdentifier: test.name)
    config.objectTypes = [LocalOfflineAsset.self]
    Realm.Configuration.defaultConfiguration = config
    // Also update the SDK's realm config to use in-memory
    TPStreamsSDK.realmConfig = config
    // Reset the ObjectManager to use the new config
    LocalOfflineAsset.manager = ObjectManager<LocalOfflineAsset>()
}

func cleanupRealm() {
    let realm = try! Realm()
    try! realm.write {
        realm.deleteAll()
    }
}

// MARK: - Asset Factories

extension Asset {
    /// Creates a minimal valid Asset for testing.
    static func make(
        id: String = "test-asset-1",
        title: String = "Test Video",
        contentType: String = "video",
        playbackURL: String = "https://example.com/video.m3u8",
        isDrmEncrypted: Bool = false,
        isAESEncrypted: Bool = false,
        duration: Double = 120.0,
        tracks: [SubtitleTrack] = [],
        folderTree: String? = "Root/Section",
        drmContentId: String? = nil
    ) -> Asset {
        let contentProtectionType: ContentProtectionType? = isDrmEncrypted ? .drm : (isAESEncrypted ? .aes : nil)
        let video = Video(
            id: id,
            playbackURL: playbackURL,
            status: "Ready",
            drmEncrypted: isDrmEncrypted,
            duration: duration,
            thumbnailURL: "https://example.com/thumb.jpg",
            contentProtectionType: contentProtectionType,
            tracks: tracks
        )
        return Asset(
            id: id,
            title: title,
            contentType: contentType,
            video: video,
            liveStream: nil,
            folderTree: folderTree,
            drmContentId: drmContentId
        )
    }

    /// Creates a minimal valid live stream Asset for testing.
    static func makeLive(
        id: String = "test-live-1",
        title: String = "Live Stream",
        hlsUrl: String = "https://example.com/live.m3u8",
        status: String = "Streaming",
        enableDRM: Bool = false,
        noticeMessage: String? = nil,
        transcodeRecordedVideo: Bool = false
    ) -> Asset {
        let liveStream = LiveStream(
            status: status,
            hlsUrl: hlsUrl,
            transcodeRecordedVideo: transcodeRecordedVideo,
            chatEmbedUrl: "https://example.com/chat",
            noticeMessage: noticeMessage,
            enableDRM: enableDRM
        )
        return Asset(
            id: id,
            title: title,
            contentType: "live",
            video: nil,
            liveStream: liveStream,
            folderTree: nil,
            drmContentId: nil
        )
    }
}

// MARK: - LocalOfflineAsset Factory

extension LocalOfflineAsset {
    /// Creates a LocalOfflineAsset for testing (does NOT persist to Realm).
    static func make(
        assetId: String = "test-asset-1",
        title: String = "Test Video",
        srcURL: String = "https://example.com/video.m3u8",
        resolution: String = "720p",
        duration: Double = 120.0,
        bitRate: Double = 1_000_000,
        status: String = Status.finished.rawValue,
        thumbnailURL: String? = "https://example.com/thumb.jpg",
        folderTree: String = "Root",
        drmContentId: String? = nil,
        contentProtectionType: ContentProtectionType? = nil,
        downloadedPath: String? = nil,
        metadata: [String: Any]? = nil
    ) -> LocalOfflineAsset {
        let asset = LocalOfflineAsset.create(
            assetId: assetId,
            srcURL: srcURL,
            title: title,
            resolution: resolution,
            duration: duration,
            bitRate: bitRate,
            thumbnailURL: thumbnailURL,
            folderTree: folderTree,
            drmContentId: drmContentId,
            contentProtectionType: contentProtectionType,
            metadata: metadata
        )
        asset.status = status
        if let path = downloadedPath {
            asset.downloadedPath = path
        }
        return asset
    }
}

// MARK: - SubtitleTrack Factory

extension SubtitleTrack {
    /// Creates a SubtitleTrack for testing.
    static func make(
        language: String = "en",
        url: String = "https://example.com/en.vtt",
        isAutoGenerated: Bool = false
    ) -> SubtitleTrack {
        SubtitleTrack(from: [
            "language": language,
            "url": url,
            "subtitle_type": isAutoGenerated ? "Auto Generated" : "Manual"
        ])!
    }
}

// MARK: - JSON Test Data

enum TestJSON {
    /// StreamsAPI video detail response.
    static let streamsVideoDetail: [String: Any] = [
        "id": "asset-123",
        "title": "Test Video Title",
        "type": "video",
        "folder_tree": "Root/Section/Lesson",
        "drm_content_id": "drm-content-123",
        "video": [
            "id": "video-456",
            "playback_url": "https://app.tpstreams.com/hls/abc123/master.m3u8",
            "status": "Ready",
            "duration": 3600.5,
            "cover_thumbnail_url": "https://example.com/thumb.jpg",
            "content_protection_type": "drm",
            "tracks": [
                ["language": "en", "url": "https://example.com/en.vtt", "subtitle_type": "Manual"],
                ["language": "es", "url": "https://example.com/es.vtt", "subtitle_type": "Auto Generated"]
            ]
        ]
    ]

    /// StreamsAPI live stream response.
    static let streamsLiveStreamDetail: [String: Any] = [
        "id": "live-789",
        "title": "Live Class",
        "type": "live",
        "live_stream": [
            "status": "Streaming",
            "hls_url": "https://example.com/live.m3u8",
            "transcode_recorded_video": true,
            "chat_embed_url": "https://example.com/chat",
            "notice_message": "Starting soon!",
            "enable_drm": false
        ]
    ]

    /// TestpressAPI video detail response.
    static let testpressVideoDetail: [String: Any] = [
        "id": "123",
        "title": "Testpress Video",
        "content_type": "video",
        "video": [
            "id": "tp-video-456",
            "hls_url": "https://org.testpress.in/hls/abc/master.m3u8",
            "transcoding_status": "Ready",
            "drm_enabled": true,
            "duration": 1800.0,
            "thumbnail_url": "https://example.com/tp-thumb.jpg",
            "content_protection_type": "drm",
            "tracks": [
                ["language": "en", "url": "https://example.com/en.vtt", "subtitle_type": "Auto Generated"]
            ]
        ]
    ]

    /// TestpressAPI live stream response.
    static let testpressLiveStreamDetail: [String: Any] = [
        "id": 456,
        "title": "Live Event",
        "content_type": "live",
        "live_stream": [
            "status": "Running",
            "stream_url": "https://example.com/live.m3u8",
            "show_recorded_video": true,
            "chat_embed_url": "https://example.com/chat",
            "notice_message": "Will start at 3PM"
        ]
    ]

    /// Response with missing required fields.
    static let malformedResponse: [String: Any] = [
        "some_field": "some_value"
    ]

    /// AES encrypted video response (StreamsAPI).
    static let streamsAESEncryptedVideo: [String: Any] = [
        "id": "aes-asset-1",
        "title": "AES Encrypted Video",
        "type": "video",
        "video": [
            "id": "aes-video-1",
            "playback_url": "https://app.tpstreams.com/hls/aes/master.m3u8",
            "status": "Ready",
            "duration": 600.0,
            "content_protection_type": "aes"
        ]
    ]

    /// Video with no tracks.
    static let videoNoTracks: [String: Any] = [
        "id": "no-tracks-asset",
        "title": "Video Without Tracks",
        "type": "video",
        "video": [
            "playback_url": "https://example.com/video.m3u8",
            "status": "Ready"
        ]
    ]
}
