//
//  TestpressAPIParserTests.swift
//  iOSPlayerSDKTests
//
//  Tests for TestpressAPIParser response parsing.
//

import XCTest
@testable import TPStreamsSDK

final class TestpressAPIParserTests: XCTestCase {

    private let parser = TestpressAPIParser()

    // MARK: - Video Detail Parsing

    func testParseVideoDetailReturnsValidAsset() throws {
        let data = try serializeJSON(TestJSON.testpressVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.id, "123")
        XCTAssertEqual(asset.title, "Testpress Video")
        XCTAssertEqual(asset.contentType, "video")
    }

    func testParseVideoDetailReturnsVideo() throws {
        let data = try serializeJSON(TestJSON.testpressVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertNotNil(asset.video)
        XCTAssertEqual(asset.video?.playbackURL, "https://org.testpress.in/hls/abc/master.m3u8")
        XCTAssertEqual(asset.video?.status, "Ready")
        XCTAssertEqual(asset.video?.duration ?? 0, 1800.0, accuracy: 0.01)
    }

    func testParseVideoDetailParsesDRMEncryptedVideo() throws {
        let data = try serializeJSON(TestJSON.testpressVideoDetail)
        let asset = try parser.parseAsset(data: data)

        XCTAssertTrue(asset.video?.drmEncrypted ?? false)
        XCTAssertEqual(asset.video?.contentProtectionType, .drm)
    }

    func testParseVideoDetailParsesSubtitleTracks() throws {
        let data = try serializeJSON(TestJSON.testpressVideoDetail)
        let asset = try parser.parseAsset(data: data)

        let tracks = asset.video?.tracks ?? []
        XCTAssertEqual(tracks.count, 1)
        XCTAssertEqual(tracks[0].language, "en")
        XCTAssertTrue(tracks[0].isAutoGenerated)
    }

    func testParseVideoDetailFallsBackToURLField() throws {
        let json: [String: Any] = [
            "id": "789",
            "title": "Video with URL field",
            "content_type": "video",
            "video": [
                "id": "v-789",
                "url": "https://example.com/video.m3u8",
                "transcoding_status": "Ready",
                "duration": 600.0
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.video?.playbackURL, "https://example.com/video.m3u8")
    }

    func testParseVideoDetailPrefersHLSUrlOverURLField() throws {
        let json: [String: Any] = [
            "id": "789",
            "title": "Video with both",
            "content_type": "video",
            "video": [
                "id": "v-789",
                "hls_url": "https://example.com/hls.m3u8",
                "url": "https://example.com/other.m3u8",
                "transcoding_status": "Ready"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.video?.playbackURL, "https://example.com/hls.m3u8")
    }

    // MARK: - Live Stream Parsing

    func testParseLiveStreamDetail() throws {
        let json: [String: Any] = [
            "id": "456",
            "title": "Live Event",
            "content_type": "live",
            "live_stream": [
                "status": "Running",
                "stream_url": "https://example.com/live.m3u8",
                "show_recorded_video": true,
                "chat_embed_url": "https://example.com/chat",
                "notice_message": "Will start at 3PM"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)

        XCTAssertEqual(asset.id, "456")
        XCTAssertEqual(asset.title, "Live Event")
        XCTAssertNotNil(asset.liveStream)
    }

    func testParseLiveStreamFields() throws {
        let json: [String: Any] = [
            "id": "456",
            "title": "Live Event",
            "content_type": "live",
            "live_stream": [
                "status": "Running",
                "stream_url": "https://example.com/live.m3u8",
                "show_recorded_video": true,
                "chat_embed_url": "https://example.com/chat",
                "notice_message": "Will start at 3PM"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)

        let liveStream = asset.liveStream
        XCTAssertEqual(liveStream?.status, "Running")
        XCTAssertEqual(liveStream?.hlsUrl, "https://example.com/live.m3u8")
        XCTAssertTrue(liveStream?.transcodeRecordedVideo ?? false)
        XCTAssertEqual(liveStream?.noticeMessage, "Will start at 3PM")
        XCTAssertFalse(liveStream?.enableDRM ?? true)
    }

    func testParseLiveStreamIsStreaming() throws {
        let json: [String: Any] = [
            "id": "456",
            "title": "Live Event",
            "content_type": "live",
            "live_stream": [
                "status": "Running",
                "stream_url": "https://example.com/live.m3u8",
                "show_recorded_video": true,
                "chat_embed_url": "https://example.com/chat"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)

        XCTAssertTrue(asset.liveStream?.isStreaming ?? false)
    }

    // MARK: - Missing Required Fields

    func testParseThrowsOnMissingID() {
        let json: [String: Any] = [
            "title": "Title",
            "content_type": "video"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnMissingTitle() {
        let json: [String: Any] = [
            "id": 123,
            "content_type": "video"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnMissingContentType() {
        let json: [String: Any] = [
            "id": 123,
            "title": "Title"
        ]
        let data = try! serializeJSON(json)
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    func testParseThrowsOnEmptyData() {
        let data = Data()
        XCTAssertThrowsError(try parser.parseAsset(data: data))
    }

    // MARK: - ID Type Handling

    func testParseHandlesIntegerVideoID() throws {
        // The asset-level ID must be a String, but video-level ID can be Int
        let json: [String: Any] = [
            "id": "42",
            "title": "Integer Video ID",
            "content_type": "video",
            "video": [
                "id": 42,
                "hls_url": "https://example.com/video.m3u8",
                "transcoding_status": "Ready"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)
        XCTAssertEqual(asset.id, "42")
        XCTAssertEqual(asset.video?.id, "42")
    }

    func testParseHandlesStringID() throws {
        let json: [String: Any] = [
            "id": "string-id",
            "title": "String ID Video",
            "content_type": "video",
            "video": [
                "hls_url": "https://example.com/video.m3u8",
                "transcoding_status": "Ready"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)
        XCTAssertEqual(asset.id, "string-id")
    }

    // MARK: - DRM Disabled Default

    func testParseLiveStreamDRMDefaultsToFalse() throws {
        let json: [String: Any] = [
            "id": "1",
            "title": "Live",
            "content_type": "live",
            "live_stream": [
                "status": "Running",
                "stream_url": "https://example.com/live.m3u8",
                "chat_embed_url": "https://example.com/chat"
            ]
        ]
        let data = try serializeJSON(json)
        let asset = try parser.parseAsset(data: data)
        XCTAssertFalse(asset.liveStream?.enableDRM ?? true)
    }

    // MARK: - Helper

    private func serializeJSON(_ dict: [String: Any]) throws -> Data {
        try JSONSerialization.data(withJSONObject: dict)
    }
}
