import Foundation

public struct SubtitleTrack {
    let language: String
    let url: String
    let isAutoGenerated: Bool
    let displayName: String

    init?(from dictionary: [String: Any]) {
        guard let language = dictionary["language"] as? String,
              let url = dictionary["url"] as? String else {
            return nil
        }

        guard let parsedURL = URL(string: url),
              parsedURL.scheme == "http" || parsedURL.scheme == "https",
              parsedURL.pathExtension.lowercased() == "vtt" else {
            return nil
        }

        self.language = language
        self.url = url
        self.isAutoGenerated = (dictionary["subtitle_type"] as? String) == "Auto Generated"
        let localizedName = Locale.current.localizedString(forLanguageCode: language) ?? language
        self.displayName = isAutoGenerated ? "\(localizedName) (Auto)" : localizedName
    }
}
