name: iOS Test

on: [push, pull_request]

jobs:
  build:
    name: Test iOS Player SDK
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        run: |
          xcodebuild test -project iOSPlayerSDK.xcodeproj -scheme iOSPlayerSDKTests -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'